version: "3"

services:
  nginx:
    image: defunctzombie/localtunnel-nginx:latest
    restart: always
    volumes:
        - ./ssls:/etc/nginx/ssl/
    networks:
      - host
    
  localtunnel:
    container_name: localtunnel
    image: defunctzombie/localtunnel-server:latest
    restart: unless-stopped
    env_file: .env
    #command: "--secure --port 3000 --domain ${DOMAIN} --landing ${LANDING}"
    command: "--port 3000 --domain ${DOMAIN} --landing ${LANDING}"
    ports:
      - '3000'
    networks:
      - host

networks:
  host:
    driver: bridge
